# This file will override base.yaml if env var "ENVIRONMENT" is not set or not "prod"
name: "Hacker Suite - Auth (dev)"
app_url: "localhost:8000"
domain_name: "localhost"
use_secure_cookies: false
auth:
  default_role: "applicant"
  email_verification_required: false
